In [8]:
import torch
import numpy as np

In [2]:
a = torch.rand(2,3)
c = torch.rand(2,3)

In [6]:
a

tensor([[0.4977, 0.6304, 0.2511],
        [0.8815, 0.9767, 0.3792]])

In [7]:
c

tensor([[0.8587, 0.8463, 0.9681],
        [0.0123, 0.9905, 0.0806]])

In [5]:
torch.mean(torch.stack([a,c]), dim=0)

tensor([[0.6782, 0.7384, 0.6096],
        [0.4469, 0.9836, 0.2299]])

In [32]:
d = a[1:, 1:]
d

tensor([[0.3416, 0.0115]])

In [27]:
c

tensor([[0.1870, 0.5383, 0.7146],
        [0.2829, 0.3306, 0.2252]])

In [34]:
d

tensor([[0.3416, 0.2252]])

In [33]:
d = torch.max(torch.stack((d,c[1:,1:])), dim=0)[0]
a[1:,1:]


tensor([[0.3416, 0.0115]])

In [10]:
mask = a > 0.5
mask = mask.permute(0,2,3,1).reshape(-1,2)
mask

tensor([[False, False],
        [False, False],
        [False,  True],
        [ True, False],
        [ True,  True],
        [ True,  True],
        [ True, False],
        [False, False],
        [ True,  True],
        [False,  True],
        [False, False],
        [False, False]])

In [7]:
b = a.permute(0,2,3,1).reshape(-1, 2)
b

tensor([[0.3499, 0.4991],
        [0.1176, 0.1442],
        [0.2104, 0.9337],
        [0.8109, 0.1749],
        [0.7113, 0.7368],
        [0.8656, 0.7422],
        [0.7713, 0.0204],
        [0.4716, 0.2170],
        [0.6876, 0.6600],
        [0.4629, 0.8268],
        [0.1265, 0.2456],
        [0.3868, 0.0211]])

In [19]:
def _gaussian2D(shape, sigma=1):
    m, n = [(ss - 1.) / 2. for ss in shape]
    y, x = np.ogrid[-m:m+1,-n:n+1]

    h = np.exp(-(x * x + y * y) / (2 * sigma * sigma))
    h[h < np.finfo(h.dtype).eps * h.max()] = 0
    return torch.from_numpy(h)    

In [72]:
def _gaussian2D(shape, sigma=1):
    m, n = [np.ceil((ss - 1.) / 2.) for ss in shape]
    y, x = np.ogrid[-m:m+1,-n:n+1]

    h = np.exp(-(x * x + y * y) / (2 * sigma * sigma))
    h[h < np.finfo(h.dtype).eps * h.max()] = 0
    return torch.from_numpy(h)   

In [20]:
a = _gaussian2D((3,3), 4/6)

In [21]:
a

tensor([[0.1054, 0.3247, 0.1054],
        [0.3247, 1.0000, 0.3247],
        [0.1054, 0.3247, 0.1054]], dtype=torch.float64)

In [86]:
a.max()

tensor(1., dtype=torch.float64)

In [77]:
e = b.clone()
e[0] = 100
b[0]

tensor([0.3499, 0.4991])

In [80]:
torch.stack([b[0]-b[0].int()])

tensor([[0.3499, 0.4991]])